import os

# Buat struktur folder app
folders = [
    "app/src/main/java/com/xyrenn/hacking/auth/models",
    "app/src/main/java/com/xyrenn/hacking/ui/dashboard/adapters",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/wifi/models",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/wifi/adapters",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/spam/models",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/spam/adapters",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/network/models",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/network/adapters",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/remote/models",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/remote/adapters",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/advanced/models",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/advanced/adapters",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/crypto/models",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/bluetooth/models",
    "app/src/main/java/com/xyrenn/hacking/ui/tools/bluetooth/adapters",
    "app/src/main/java/com/xyrenn/hacking/ui/history/models",
    "app/src/main/java/com/xyrenn/hacking/ui/stats/models",
    "app/src/main/java/com/xyrenn/hacking/ui/settings/models",
    "app/src/main/java/com/xyrenn/hacking/ui/settings/adapters",
    "app/src/main/java/com/xyrenn/hacking/core",
    "app/src/main/java/com/xyrenn/hacking/data/models",
    "app/src/main/java/com/xyrenn/hacking/data/repository",
    "app/src/main/java/com/xyrenn/hacking/data/local/dao",
    "app/src/main/java/com/xyrenn/hacking/data/local/entities",
    "app/src/main/java/com/xyrenn/hacking/data/local/preferences",
    "app/src/main/java/com/xyrenn/hacking/data/local/converters",
    "app/src/main/java/com/xyrenn/hacking/data/remote/api/models",
    "app/src/main/java/com/xyrenn/hacking/data/remote/socket",
    "app/src/main/java/com/xyrenn/hacking/utils/extensions",
    "app/src/main/java/com/xyrenn/hacking/utils/helpers",
    "app/src/main/java/com/xyrenn/hacking/utils/managers",
    "app/src/main/java/com/xyrenn/hacking/utils/security",
    "app/src/main/java/com/xyrenn/hacking/utils/constants",
    "app/src/main/java/com/xyrenn/hacking/services",
    "app/src/main/java/com/xyrenn/hacking/receivers",
    "app/src/main/java/com/xyrenn/hacking/workers",
    "app/src/main/res/layout/auth",
    "app/src/main/res/layout/dashboard",
    "app/src/main/res/layout/tools/wifi",
    "app/src/main/res/layout/tools/spam",
    "app/src/main/res/layout/tools/network",
    "app/src/main/res/layout/tools/remote",
    "app/src/main/res/layout/tools/advanced",
    "app/src/main/res/layout/tools/crypto",
    "app/src/main/res/layout/tools/bluetooth",
    "app/src/main/res/layout/history",
    "app/src/main/res/layout/stats",
    "app/src/main/res/layout/settings",
    "app/src/main/res/layout/item",
    "app/src/main/res/drawable",
    "app/src/main/res/drawable-v24",
    "app/src/main/res/menu",
    "app/src/main/res/font",
    "app/src/main/res/anim",
    "app/src/main/res/xml",
    "app/src/main/res/raw",
    "app/src/main/res/navigation",
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)
    print(f"Created: {folder}")

print("\n✅ Struktur folder app berhasil dibuat!")
print("Sekarang tinggal copy paste file .kt dan .xml dari chat GOSAN")